env: dev
log_level: debug
http_srv:
  address: :8800
  keep_alive: true
  read_timeout: 30s
  write_timeout: 30s
db:
  driver: "mysql"
  database: "naive-admin"
  username: "root"
  password: "Man10f&3^H_98est$"
  host: "10.17.21.132"
  port: 3306
  max_idle_conns: 5
  max_open_conns: 10
  conn_max_lifetime: 3600