env: dev
log_level: debug
http_srv:
  address: :8800
  keep_alive: true
  read_timeout: 30s
  write_timeout: 30s
db:
  driver: "mysql"
  database: "naive_admin"
  username: "root"
  password: "123456"
  host: "127.0.0.1"
  port: 3306
  max_idle_conns: 5
  max_open_conns: 10
  conn_max_lifetime: 3600